CovidShield/mobile

- README.md
This should be the proper way to install pods to avoid issues with different versions.
> Update install instructions to use bundler and yarn pod-install script

- src/locale/translations/fr.json
Translated text from this PR https://github.com/CovidShield/mobile/pull/14
> Translated (french) "ThankYou" sheet content

- src/testMode/TestMode.tsx
This PR removes language in test menu because it is the main functionality of the app already.
> Remove Language in TestMenu

- package.json
Make run-android command consistent
> Fix run-android command

- android/app/build.gradle
- src/testMode/TestMode.tsx
- src/testMode/views/Item.tsx
This significantly improves app size and startup time. See for more info: https://hermesengine.dev/.
Hermes is pretty compatible with the current ecosystem, the main incompatibility is with OTA update services like CodePush. The other problematic one is crash reporting, but Sentry has good support for it. The app currently does not include any of these functionalities so it should not be a problem.
> Enable hermes on Android

- src/index.ts
Those were the 2 warnings I found that were not actionable.
> Use YellowBox.ignoreWarnings instead of completely disabling it

- .env
- .env.production
- src/env/index.ts
- src/testMode/MockProvider.tsx
- src/testMode/views/Item.tsx
This PR fixes mock server initial value by using .env. It also fixes .env.production.
> Fix env and mock server

- src/locale/translations/fr.json
Based on the second translator's review.
> Update french translation

- android/app/src/main/java/app/covidshield/module/CovidShieldModule.kt
- src/services/ExposureNotificationService/ExposureNotificationService.ts
Resolve https://github.com/CovidShield/mobile/issues/75
> Fix crash on Android release build

- src/components/Button.tsx
fixes https://github.com/CovidShield/mobile/issues/58
> Indicate disabled button state in voice-over mode

- package.json
Follow up of https://github.com/CovidShield/mobile/pull/107
> Follow PR fixing package.json

- src/screens/tutorial/TutorialContent.tsx
This updates the pause frames for users with reduced motion enabled.
> Update pause frames for new animations for users with reduced motion

- design/illustrator/Illustrations.ai
Updated illustrations + Dark mode illustrations
> Dark mode illustrations updated

- src/components/BottomSheet/BottomSheet.tsx
- src/components/TouchableIcon.tsx
- src/screens/home/views/InfoShareView.tsx
- src/screens/sharing/Sharing.tsx
Adds accessibilityRole prop for last remaining Touchable components
Closes https://github.com/CovidShield/mobile/issues/4
> Add last missing accessibilityRole props for Touchables

- README.md
See https://developer.apple.com/xcode/
> Use correct spelling of Xcode in readme

- android/app/src/main/java/app/covidshield/module/ExposureNotificationModule.kt
- src/App.tsx
- src/locale/i18n.ts
- src/screens/home/views/OverlayView.tsx
Cherry-pick from https://github.com/cds-snc/covid-shield-mobile/pull/99
Resolves https://github.com/CovidShield/mobile/issues/137
> Ensure bluetooth turn on and off properly along with ExposureNotification on Android

- src/services/ExposureNotificationService/ExposureNotificationService.ts
> Designated initial exposure system status

- src/components/InfoBlock.tsx
This PR fixes tex alignment, also verified accessibility on Android in related change.
Resolves https://github.com/CovidShield/mobile/issues/112
> Fix text alignment

- android/settings.gradle
- ios/Podfile
- package.json
- src/App.tsx
- src/locale/index.ts
- src/locale/locale.ts
- src/services/StorageService/StorageService.ts
- src/services/StorageService/StorageServiceProvider.tsx
- yarn.lock
Resolves https://github.com/CovidShield/mobile/issues/111 and https://github.com/cds-snc/covid-shield-mobile/issues/91
> Use system locale as default locale

- android/build.gradle
- package.json
- patches/react-native-system-setting+1.7.4.patch
- yarn.lock
Follow up https://github.com/CovidShield/mobile/pull/164
> Patch Android for release

- src/index.ts
Disable warning from `react-native-zip-archive`
> Disable warning about zipArchiveProgressEvent

- src/services/ExposureNotificationService/ExposureNotificationService.ts
This PR fixes:
- Only show local push notification when exposureStatus changes from monitoring to exposed. 
- `update...` method isn't meant to return value. So, I remove return type. 
Resolves https://github.com/CovidShield/mobile/issues/181
> Fix local push notification

- src/index.ts
- src/services/ExposureNotificationService/ExposureNotificationService.ts
Resolves https://github.com/CovidShield/mobile/issues/183
> Fix exposureStatus initial state in android headless task

- src/services/ExposureNotificationService/ExposureNotificationService.spec.ts
- src/services/ExposureNotificationService/ExposureNotificationService.ts
- src/services/ExposureNotificationService/ExposureNotificationServiceProvider.tsx
- src/testMode/TestMode.tsx
Resolves https://github.com/CovidShield/mobile/issues/188
> Clean up diagnosed state

- TEST_PLAN.md
Follow up https://github.com/CovidShield/mobile/pull/190
> Fix Test Plan

- src/services/BackendService/BackendService.spec.ts
- src/services/BackendService/BackendService.ts
Resolves https://github.com/CovidShield/mobile/issues/192
> Fix keys upload limit

- src/services/ExposureNotificationService/ExposureNotificationService.ts
Follow up of https://github.com/cds-snc/covid-shield-mobile/pull/372
> Skip server upload if diagnosisKeys is empty

- ios/CovidShield/CovidShield.m
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/430
> Fix memory leak in getRandomBytes iOS

- android/app/src/main/java/app/covidshield/extensions/TimerExtensions.kt
- android/app/src/main/java/app/covidshield/module/ExposureNotificationModule.kt
- src/services/ExposureNotificationService/ExposureNotificationService.ts
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/454
> Add timeout to detect exposure bridge on Android

- src/services/ExposureNotificationService/DefaultExposureConfiguration.json
- src/services/ExposureNotificationService/ExposureNotificationService.ts
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/463
> More robust handling of the exposureConfiguration download

- android/app/src/main/java/app/covidshield/module/PushNotificationModule.kt
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/477
> Fix notification priority on Android

- src/bridge/PushNotification.ts
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/482
> Prevent showing multiple notifications on iOS

- src/locale/translations/fr.json
Follow up of https://github.com/CovidShield/mobile/pull/186
> Follow up translation

- android/app/build.gradle
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/501
> Support bundle in debug for Android

- src/services/BackendService/BackendService.ts
- src/shared/fetch.ts
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/513
> Adding `cache-control` headers to fetch / blobFetch requests

- src/screens/home/components/NotificationPermissionStatus.tsx
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/538
> Fix notification permission is out of synced

- src/index.ts
- src/services/ExposureNotificationService/ExposureNotificationService.ts
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/572
> Attempt to fix push notification

- src/services/ExposureNotificationService/ExposureNotificationService.ts
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/610
> Fix EN popup

- src/App.tsx
- src/bridge/ExposureNotification/ExposureNotificationAdapter.android.ts
- src/bridge/ExposureNotification/ExposureNotificationAdapter.ios.ts
- src/locale/i18n.ts
- src/screens/home/views/DiagnosedShareView.tsx
- src/screens/home/views/DiagnosedView.tsx
- src/screens/home/views/ExposureView.tsx
- src/screens/home/views/InfoShareView.tsx
- src/services/BackendService/BackendService.ts
- src/services/BackgroundSchedulerService/BackgroundSchedulerService.ts
- src/services/ExposureNotificationService/ExposureNotificationService.ts
- src/shared/log.ts
- src/testMode/TestMode.tsx
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/643 and https://github.com/cds-snc/covid-shield-mobile/pull/555
> Fix detectExposure and extract usage of console.log

- android/app/src/main/java/app/covidshield/module/CovidShieldModule.kt
- ios/CovidShield/CovidShield.m
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/660
> Fix random bytes reject

- android/app/src/main/java/app/covidshield/MainActivity.kt
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/665
> Fix crash when changing front size

- package.json
- patches/react-native-background-fetch+3.1.0.patch
- yarn.lock
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/693
> Use latest react-native-background-fetch
