CovidShield/mobile

src/locale/translations/en.json

Add `ThankYou` content for bottom sheet to be displayed one time, post-onboarding. Reassures user that exposure notifications are on, and tells them that COVID Shield will send a notification if it detects that they have possibly been exposed to COVID-19.

Add "ThankYou" sheet content

---

ios/Config.debug.xcconfig
ios/Config.release.xcconfig

On the first build this file does not exist since it is generated in the script phases later.
This is what is recommended in the react-native-config docs https://www.npmjs.com/package/react-native-config#availability-in-build-settings-and-infoplist

Fix missing Generated.xcconfig file error on initial build

---

src/locale/translations/en.json

Change `NoConnectivity` from "COVID Shield is offline" to "No internet connection" to more clearly reflect situation: exposure notifications and Bluetooth are on, the app is on, but no future exposure checks can occur until there is an internet connection available.
Update to French translation, if needed, will be in separate PR.

Replace "NoConnectivity" string

---

src/locale/translations/fr.json

Change NoConnectivity from "COVID Shield est hors ligne" (COVID Shield is offline) to "Aucune connexion Internet" (No internet connection) to more clearly reflect situation: exposure notifications and Bluetooth are on, the app is on, but no future exposure checks can occur until there is an internet connection available.
English update to same string is PR #8

Replace "NoConnectivity" string (French)

---

.eslintrc.js
src/components/CodeInput.tsx
src/screens/datasharing/views/FormView.tsx

I think this improves UX since it is the only input on the screen. There is a lint rule agains the autoFocus prop but I think this is for react web. If there is a reason for not using autofocus here feel free to close this.

Autofocus code input

---

ios/Podfile.lock
package.json
src/components/Toolbar.tsx
src/navigation/MainNavigator.tsx
yarn.lock

Native stack uses native UIViewController and Fragment to handle screen transitions. It has the same api as react-navigation stack, just slightly different config options. This also enables react-native-screens which helps with performance by doing things like unmounting views that are not focused. See https://github.com/software-mansion/react-native-screens/tree/master/native-stack.
We also get the new iOS 13 modal design.
Test modal screens manually
New modal design
No changes

Use react-navigation native stack

---

ios/CovidShield/ExposureNotification.m

This fixes a crash when reloading the app on iOS.
Open dev menu -> reload -> no crash 🎉

Invalidate EnManager on app reload

---

src/App.tsx
src/navigation/DevPersistedNavigationContainer.tsx

This implements state persistence for navigation in development. This means doing a full reload will restore the navigation in the state it was before. Based on https://reactnavigation.org/docs/state-persistence. 
Open the language screen on do a full reload, lang screen reopens.

Persist navigation state in dev

---

src/screens/home/HomeScreen.tsx

This is easier than clicking the icon and accessible from anywhere.
Do we still want to keep the action on the icon?
Open RN dev menu -> Show Test Menu -> Test menu opens

Add item to show the test menu from RN dev menu

---

ios/CovidShield/AppDelegate.m

Sets the default tint color to link blue. This will be used instead of the apple blue which is the default.
For example in the share sheet, see "Edit Actions..."
Before:
After:

Set default tint color on iOS

---

index.js
src/index.ts

This will avoid including the Intl polyfill in the bundle on iOS. The polyfill is actually only needed when using Hermes on Android so it could be completely removed in case we decide to keep using JSC (#33).
Moved the polyfill to index.js since the file uses require it makes it easier to conditionally require the polyfill. Imports get hoisted so it would not be possible to make sure the intl polyfill code runs before any other code.

Only include Intl polyfill on Android

---

src/locale/translations/fr.json

`pour` has been replaced by `pendant` based on the latest review.

Update to the french translation

---

android/app/src/main/AndroidManifest.xml
src/components/BottomSheet.tsx
src/components/Header.tsx
src/screens/home/HomeScreen.tsx
src/screens/home/components/BaseHomeView.tsx
src/screens/home/views/OverlayView.tsx
src/screens/onboarding/Onboarding.tsx
src/screens/tutorial/Tutorial.tsx
src/screens/tutorial/TutorialContent.tsx
src/shared/theme.ts
src/shared/useMaxContentWidth.ts
src/shared/useOrientation.ts

Related to: https://github.com/CovidShield/mobile/issues/11
1. enable landscape orientation for Android by changing `screenOrientation` in the manifest from `portrait` to `unspecified`
2. Areas around the app that used the static `Dimensions` object have been changed to use the `useWindowDimensions` hook in order to be dynamic
3. In HomeScreen conditionally show lottieView
4. HomeScreen/BottomSheet maxWidth 500 when landscape
5. Onboarding maxWidth 500 when landscape
BottomSheet was tricky - when using percent snapPoints the `BottomSheetRaw` component doesn't seem to update its internal height/width values that it uses to evaluate the points based on percent when screen dimensions change (see this issue for related discussion: https://github.com/osdnk/react-native-reanimated-bottom-sheet/i …

Enable landscape orientation for android

---

ios/CovidShield/ExposureNotification.m
src/screens/home/HomeScreen.tsx
src/services/ExposureNotificationService/ExposureNotificationService.ts
src/services/ExposureNotificationService/ExposureNotificationServiceProvider.tsx

We were not calling `setExposureNotificationEnabled` which is a required to step to enable the framework on iOS. 
Once fixed, I realized we start up EN stack at app paunch which isn't ideal, since we need to get user a chance to go through onboarding messaging first. I moved start up to later, when onboarding is finished.

Fix EN framework start-up

---

src/services/StorageService/StorageServiceProvider.tsx
src/testMode/TestMode.tsx

Because of navigation persistance the reset app dev action does not work well since it will clear data but return to the main app still.
A good workaround I found is to reload the app immediately after clearing storage. We can also now remove the message that says you need to reload the app manually.

Fix test mode reset data

---

src/components/Button.tsx
src/components/ProgressCircles.tsx
src/screens/onboarding/Onboarding.tsx
src/screens/onboarding/views/Permissions.tsx
src/screens/onboarding/views/Start.tsx
src/screens/tutorial/Tutorial.tsx

This PR fixes Next button alignment in both Onboarding and Tutorial screen. It also removes background image in boarding screen.
Resolves:
- https://github.com/CovidShield/mobile/issues/59
- https://github.com/CovidShield/mobile/issues/61

Fix button and background in onboarding and tutorial screen

---

android/app/build.gradle

Because package name in Android needs to be whitelisted, it is annoying to automatically add prefix to package name.

Disable application prefix for debug build

---

src/screens/home/HomeScreen.tsx
src/screens/home/views/ExposureNotificationsDisabledView.tsx
src/screens/onboarding/Onboarding.tsx
src/services/ExposureNotificationService/ExposureNotificationService.spec.ts
src/services/ExposureNotificationService/ExposureNotificationService.ts
src/services/ExposureNotificationService/ExposureNotificationServiceProvider.tsx

This PR does two things:
- Show EN dialog at the end of onboarding flow. 
- Attempt to fix flashing system status when open the app. Although there is still on flashing due to internet check but it should be in a follow up PR. 
- Change APP_ID_ANDROID to `com.google.android.apps.exposurenotification`.
- Run the app. 
- Verify:
+ A consent dialog is shown at the end of onboarding flow.
+ System status is updated properly when disable EN in settings and resume the app. 
+ Able to re-enable EN in app after disabling EN in settings.
https://drive.google.com/file/d/17wJ_1b7zrIcOcaC-ycgaIfwfUzjLsWbt/view?usp=sharing
Resolves https://github.com/CovidShield/mobile/issues/117 and https://github.com/CovidShield/mobile/issues/118

Show EN dialog at the end of onboarding flow

---

.env
.env.production
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/app/covidshield/extensions/PromiseExtensions.kt
android/app/src/main/java/app/covidshield/extensions/ReactNativeExtensions.kt
android/app/src/main/java/app/covidshield/extensions/TemporaryExposureKeyExtensions.kt
android/app/src/main/java/app/covidshield/models/ExposureKey.kt
android/app/src/main/java/app/covidshield/module/CovidShieldModule.kt
android/app/src/main/java/app/covidshield/module/ExposureNotificationModule.kt
android/app/src/main/java/app/covidshield/module/PushNotificationModule.kt
package.json
src/App.tsx
src/bridge/ExposureNotification.ts
src/env/index.ts
src/index.ts
src/services/BackendService/BackendService.ts
src/services/BackendService/covidshield/covidshield.d.ts
src/services/BackendService/covidshield/covidshield.js
src/services/BackendService/covidshield/covidshield.proto
src/services/ExposureNotificationService/ExposureNotificationService.spec.ts
src/services/ExposureNotificationService/ExposureNotificationService.ts
src/shared/date-fns.ts
yarn.lock

This PR fixes submission flow on Android and polishes the bridge.
Resolves https://github.com/CovidShield/mobile/issues/123
Cherry-pick js changes in here https://github.com/CovidShield/mobile/pull/102 and resolve broken schema. 
- Checkout `https://github.com/CovidShield/server`, make sure all dependencies are installed (check dev.ym#up), and run the server.
- Use `ngrok` to tunnel server endpoint
```
ngrok http 8000
ngrok http 8001
```
- In this PR, changes `.env` to (use your ngrok urls)
```
APP_ID_IOS=app.covidshield
APP_ID_ANDROID=com.google.android.apps.exposurenotification
APP_VERSION_CODE=1
APP_VERSION_NAME=1.0
SUBMIT_URL=https://2c4c45ae1a78.ngrok.io
RETRIEVE_URL=https://2a78ac7e6310.ngrok.io
HMAC_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa …
```

Fix submission flow on Android

---

src/services/StorageService/StorageService.ts

Selected region was being persisted to AsyncStorage with wrong key - update to use correct key. Think this went unnoticed since region isn't really used in app so far, and it is set prior to any locale changes.

Fix persisting region with wrong key

---

android/app/src/main/java/app/covidshield/extensions/FileExtensions.kt
android/app/src/main/java/app/covidshield/extensions/LogExtensions.kt
android/app/src/main/java/app/covidshield/extensions/ReactNativeExtensions.kt
android/app/src/main/java/app/covidshield/extensions/TemporaryExposureKeyExtensions.kt
android/app/src/main/java/app/covidshield/models/ExposureKey.kt
android/app/src/main/java/app/covidshield/module/CovidShieldModule.kt
android/app/src/main/java/app/covidshield/module/ExposureNotificationModule.kt
package.json
src/bridge/ExposureNotification.ts
src/screens/home/views/OverlayView.tsx
src/services/BackendService/BackendService.ts
src/services/BackendService/covidshield/covidshield.d.ts
src/services/BackendService/covidshield/covidshield.js
src/services/BackendService/covidshield/covidshield.proto
src/services/ExposureNotificationService/ExposureNotificationService.spec.ts
src/services/ExposureNotificationService/ExposureNotificationService.ts
src/shared/date-fns.ts
yarn.lock

This PR fixes retrieval flow on Android. 
Resolves https://github.com/CovidShield/server/issues/70
- Run server locally https://github.com/CovidShield/server
- Connect mobile to local server via ngrok by changing `.env` file. 
- Change APP_ID to `com.google.android.apps.exposurenotification`.
- Make sure your device / account has EN enable. 
- Make sure `By pass signature check` is ON or `Enable app signature check` is OFF in debug mode (see screenshots below).
- Open app on Android device. 
- In `Test menu`, press `Clear exposure history and run check`. 
- You might need to set a couple of console.log in `ExposureNotificationService#performExposureStatusUpdate` to verify that the file is sent to the framework properly.
- Setup: I have 2 android devices running EN.
- The 1st device is set …

Fix retrieval flow on Android

---

src/screens/home/HomeScreen.tsx

Per https://github.com/react-native-community/react-native-netinfo/issues/295 
initial network status is wrongly `false` which causes screen flickering:

Check if initial status is correct

---

src/App.tsx
src/services/StorageService/StorageService.ts
src/services/StorageService/StorageServiceProvider.tsx

Functional component just rerenders everything by default when the useStorage hook changes, we don't want that here. Instead we only want to check for local from storage on app init and update it as needed from context.
Closes https://github.com/CovidShield/mobile/issues/146

Fix locale behaviour so everything doesn't get rerendered on locale change

---

.env
android/settings.gradle
ios/Podfile
package.json
src/screens/home/HomeScreen.tsx
src/services/ExposureNotificationService/ExposureNotificationService.spec.ts
src/services/ExposureNotificationService/ExposureNotificationService.ts
src/services/ExposureNotificationService/ExposureNotificationServiceProvider.tsx
src/types/react-native-system-setting.d.ts
yarn.lock

This PR fixes system status initial state. The system status flashing issue is related to async loading in ExposureNotificationService. The initial value is Disable for systemStatus and Monitoring for expsoureStatus, then we call start to load actual data. I fixes it by separating init and start. 
Follow up of https://github.com/CovidShield/mobile/pull/138 and https://github.com/CovidShield/mobile/pull/139
Resolves https://github.com/cds-snc/covid-shield-mobile/issues/95
- Run the app. 
- Pull down notification bar, disable bluetooth.
- Verify that system status changes to Bluetooth turn off.

Fix system status initial state

---

src/screens/datasharing/DataSharing.tsx

This PR fixes keyboard blocks button onClick event which requires to tap on screen twice to submit event. 
Resolves https://github.com/CovidShield/mobile/issues/141

Fix keyboard blocks button onClick

---

src/components/BottomSheet/BottomSheet.tsx
src/components/BottomSheet/SheetContentsContainer.tsx
src/screens/home/HomeScreen.tsx

BottomSheet we use take `renderContent` function, it's used for rendering content on demand. We used to give it statically rendered ReactElement, and when that element needs to change we would re-render the whole bottom sheet, which isn'r right: bottom sheet has animation and transitions side effects which clash with re-rendering. 
Instead, I give ComponentType to which will be used by bottom sheet to render content. Since it's component with no props, whenever it needs to update itself (based on system status change) it will only re-render itself, and bottom sheet structure will remain intact.

Refactor bottom sheet to support dynamic content

---

src/bridge/ExposureNotification.ts
src/screens/home/HomeScreen.tsx
src/services/ExposureNotificationService/ExposureNotificationService.ts

This is relevant for simulator mostly, but also when app is run on devices without entitlements or provisioning.
The way it's done is by using explicit Undefined status to differentiate between 'unknown' status (reported by EN when it can't start for some reason) and between initial system status before framework returned anything.

Fix SystemStatus indication when EN framework cannot start

---

ios/CovidShield/ExposureNotification.m

Turned out EN framework on iOS doesn't like configuration with NSNumbers in array wrapping double values vs int values. So picky. 
Fixed by re-packing NSNumbers with statically typed int values.

Fix exposure configuration serialization for iOS

---

ios/Podfile.lock
package.json
src/bridge/ExposureNotification.ts
src/bridge/ExposureNotificationAPI.ts
src/bridge/ExposureNotificationAdapter.android.ts
src/bridge/ExposureNotificationAdapter.d.ts
src/bridge/ExposureNotificationAdapter.ios.ts
src/services/ExposureNotificationService/ExposureNotificationService.ts
yarn.lock

I added adapter around ExposureNotification bridge so that it adds additional platform-specific behaviour (and unzipping downloaded files is such a behaviour on iOS)

Refactor: add unzipping downloaded key data files but only for iOS.

---

src/components/BottomSheet/BottomSheet.tsx
src/screens/home/HomeScreen.tsx
src/screens/home/components/NotificationPermissionStatus.tsx
src/shared/cancellablePromise.ts

This PR fixes notification permission due to state change but there is no listener. After refactoring BottomSheet setup in HomeScreen, the notification permission status is out of sync between different part of the UI as there is no listener for state change. The fix is to create react Context to unify them. 
Resolves https://github.com/CovidShield/mobile/issues/159 and https://github.com/cds-snc/covid-shield-mobile/issues/161
https://drive.google.com/file/d/1TOD1Aym2ik0qGeJ8P1JMOOl8bDrs6KWI/view?usp=sharing
https://drive.google.com/file/d/13YqPnphNpy9hTrdC1wAkwsK4lNWvrkn7/view?usp=sharing

Fix notification permission due to inconsistent state change

---

package.json
patches/react-native-system-setting+1.7.4.patch
yarn.lock

system-setting library checks many different APIs for if it's enabled or not, including `CLLocationManager`.
Although there is never an attempt to ENABLE location services, apple may statically check _any_ references to CLLocationManager symbol and flag this activity. 
Solved to excluding this API reference (and statically returning NO instead of `[CLLocationManager isEnabled]`. Since this requires modification of a library code, patched it using `patch-package`.

Patch system-setting to not reference CLLocationManager

---

src/screens/home/HomeScreen.tsx
src/screens/home/components/NotificationPermissionStatus.tsx

This PR fixes notification permission initial state.
- `noop` is passed through `useState` in a wrong way.
- Optimize useEffect to prevent NotificationPermissionStatusContext.Provider children is re-rendered. 
- Fixed CollapsedContent.

Fix notification permission initial state

---

src/index.ts
src/services/ExposureNotificationService/ExposureNotificationService.spec.ts
src/services/ExposureNotificationService/ExposureNotificationService.ts
src/services/ExposureNotificationService/ExposureNotificationServiceProvider.tsx

they way to stripped `translate` out of i18n made it unusable, attempt to call that `translate` later caused runtime crash (complaining about undefined `this.onError`.

Fix crash on attempt to use translate in ExposureNotificationService 

---

src/components/LastCheckedDisplay.tsx
src/screens/home/views/DiagnosedView.tsx
src/services/ExposureNotificationService/ExposureNotificationService.spec.ts
src/services/ExposureNotificationService/ExposureNotificationService.ts
src/shared/Observable.ts

Resolves https://github.com/CovidShield/mobile/issues/176
Tested on Android, the app switch to being exposed right after finish onboarding and the state is persisted after reopening the app. 
Note: I change local database to return TEKs for current date by remove this logic https://github.com/CovidShield/server/blob/master/pkg/server/retrieve.go#L83. If I don't do this, I need to test on the next date.

Persist exposureStatus

---

src/locale/translations/en.json

Simplify "share your random IDs" screen and notifications copy for subsequent days after initial upload.
Make 8 digit code error less repetitive.
No translations necessary.

Content updates

---

src/locale/translations/fr.json

This adds the ShareIDsCard and PermissionsError keys, with English placeholder text. The placeholder text will be replaced with French text within the next few days. For details, see #185.
@annemarieleger @Guillaumegranger1

Add ShareIDsCard and PermissionsError (French)

---

src/locale/translations/en.json

Add ShareIDsCardTitle, ShareIDsCardBody, ShareIDsCardAction to create new card for cases when a user successfully completed the 8 digit code authorization step but did not complete the flow to share their random IDs. 
Add PermissionsErrorTitle, PermissionsErrorBody, PermissionsErrorAction to create new error messaging during share random IDs flow. This will only be surfaced for errors in the permissions stages, not the 8 digit code authorization step.
More details in #149.

Add ShareIDsCard and PermissionsError

---

src/components/LastCheckedDisplay.tsx
src/services/ExposureNotificationService/ExposureNotificationService.spec.ts
src/services/ExposureNotificationService/ExposureNotificationService.ts

This PR splits lastChecked to `lastCheckedTimestamp` for displaying UI and `lastCheckedPeriod` for actual server request. 
Resolves https://github.com/CovidShield/mobile/issues/193
🎩-ed

Fix lastChecked for exposed status

---

android/app/src/main/java/app/covidshield/module/CovidShieldModule.kt

This PR fixes downloadDiagnosisKeysFile resource leak
Resolves https://github.com/cds-snc/covid-shield-mobile/issues/307

Fix downloadDiagnosisKeysFile resource leak

---

src/screens/regionPicker/RegionPicker.tsx

I didn't see similar issue in our repo but it's good to fix padding bottom.
Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/385

Fix padding in region picker

---

src/components/Text.tsx
src/screens/tutorial/Tutorial.tsx
src/screens/tutorial/TutorialContent.tsx

Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/496 and https://github.com/cds-snc/covid-shield-mobile/pull/392/files
It also fixes auto focus accessibility in Text component
Accessibility is scoped to page, not screen. That means when accessibility is on, user cannot swipe to next screen. They need to press next button.

Fix accessibility in carousel

---

ios/CovidShield/CovidShield.m

Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/524 but only for iOS.

Handling the `reject` of getRandomBytes for iOS

---

src/services/BackendService/BackendService.ts
src/shared/fetch.ts

Cherry-pick https://github.com/cds-snc/covid-shield-mobile/pull/546

Adding `cache-control` headers to fetch / blobFetch requests. (Fixed)

---

ios/Podfile.lock

Follow up of https://github.com/CovidShield/mobile/pull/220

Fix podfile when using latest background-fetch
